// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCheX9cw2Jg0ca8M0oEcGeOHZZ9tskSIg',
    appId: '1:476230904659:web:6d397088775a03d9f94fa6',
    messagingSenderId: '476230904659',
    projectId: 'yorhia-project',
    authDomain: 'yorhia-project.firebaseapp.com',
    storageBucket: 'yorhia-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhkL7fg1Jo424DbBllz2C6nybZF4cQ04',
    appId: '1:476230904659:android:515e53bfb5b61622f94fa6',
    messagingSenderId: '476230904659',
    projectId: 'yorhia-project',
    storageBucket: 'yorhia-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeBKBVq61xlgVx_zOLtdkVttWdNcxlA18',
    appId: '1:476230904659:ios:b738613b5bd478cef94fa6',
    messagingSenderId: '476230904659',
    projectId: 'yorhia-project',
    storageBucket: 'yorhia-project.appspot.com',
    iosBundleId: 'com.example.yorhia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeBKBVq61xlgVx_zOLtdkVttWdNcxlA18',
    appId: '1:476230904659:ios:b738613b5bd478cef94fa6',
    messagingSenderId: '476230904659',
    projectId: 'yorhia-project',
    storageBucket: 'yorhia-project.appspot.com',
    iosBundleId: 'com.example.yorhia',
  );
}
